Phase 1

In [10]:
import pandas as pd 
df = pd.read_csv("customers_data.csv")
df.shape

(7043, 21)

In [11]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [12]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [14]:
# discovering the target variable distribution
df["Churn"].value_counts(dropna=False)
#imbalanced

Churn
No     5174
Yes    1869
Name: count, dtype: int64

phase 2

In [15]:
# customerID
# --> identifies each customer uniquely 
# --> not categorical             --> stays str 
# --> must be unique              --> check later (todo in phase 3) 
# --> not used for churn analysis --> drop later  (todo in phase 4)
df[["customerID"]]

      customerID
0     7590-VHVEG
1     5575-GNVDE
2     3668-QPYBK
3     7795-CFOCW
4     9237-HQITU
...          ...
7038  6840-RESVB
7039  2234-XADUH
7040  4801-JZAZL
7041  8361-LTMKD
7042  3186-AJIEK

[7043 rows x 1 columns]

In [16]:
# gender :
# nominal categorical             --> stays str
# note that males & female are almost equal in number
df["gender"].value_counts(dropna=False)

gender
Male      3555
Female    3488
Name: count, dtype: int64

In [17]:
'''
converting columns to bool : 
check all values having  (0,1) representing (true,false)                        int --> bool
check all values having  (yes/no)  only                                         str --> bool
check all values having  (no internet service/no phone service) only  combine + str --> bool
'''

'\nconverting columns to bool : \ncheck all values having  (0,1) representing (true,false)                        int --> bool\ncheck all values having  (yes/no)  only                                         str --> bool\ncheck all values having  (no internet service/no phone service) only  combine + str --> bool\n'

In [18]:
# SeniorCitizen :
# indicates whether the customer is a senior citizen (age >= 60)
# values: 1,0
# 1 if the customer is a senior citizen (age >= 60), else 0
# convert int --> bool
# converting prevents doing arithmeic calculations on a categorical variable
df["SeniorCitizen"].value_counts(dropna=False)

SeniorCitizen
0    5901
1    1142
Name: count, dtype: int64

In [19]:
# Partner :
# indicates whether the customer has a partner
# values: Yes, No
# "Yes" if the customer has a partner, else "No"
# convert str --> bool
df["Partner"].value_counts(dropna=False)

Partner
No     3641
Yes    3402
Name: count, dtype: int64

In [20]:
# Dependents :
# indicateswhether the customer has dependents or not for example children or parents 
# values: Yes, No
# "Yes" if the customer has dependents, else "No"
# convert str --> bool
df["Dependents"].value_counts(dropna=False)

Dependents
No     4933
Yes    2110
Name: count, dtype: int64

In [21]:
# PhoneService :
# indicates if the customer has a phone service 
# values: Yes, No
# "Yes" if the customer has phone service, else "No"
# convert str --> bool
df["PhoneService"].value_counts(dropna=False)

PhoneService
Yes    6361
No      682
Name: count, dtype: int64

In [22]:
# MultipleLines :
# having more than one phone line
# values: Yes, No, No phone service
# "No phone service" actually means No multiple lines -> same as "No"
# PhoneService column tells us about the existence of the service so no need for "No phone service" --> reduces redunduncy
# nominal categorical  -> bool (after merging "No phone service" with "No")
df["MultipleLines"].value_counts(dropna=False)

MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

In [23]:
# InternetService:
# values: DSL, Fiber optic, No
# "DSL" and "Fiber optic" indicate the customer has internet (type specified), "No" indicates no internet
# nominal categorical (3 categories) -> stays str
# i can extract a more general feature from InternetService indicating whether the customer has internet service or not (no type specified)
# new feature --> has_internet_service (to do in phase 5)
df["InternetService"].value_counts(dropna=False)

InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

In [24]:
# OnlineSecurity :
# values: Yes, No, No internet service
# No internet service if the reason of not having OnlineSecurity is "no internet service"        --> inconsistant category
# i can map the "No internet service" to "No" (combine)
# the reason of not having the service will appear in new column extracted (has_internet_service) as demonistrated above
# after combining --> 2 categories (Yes,No) --> convert str -->  bool  
df["OnlineSecurity"].value_counts(dropna=False)

OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

In [25]:
# OnlineBackup :
# values: Yes, No, No internet service
# No internet service if the reason of not having OnlineBackup is "no internet service"        --> inconsistant category
# (same as above)
# (same as above)
# (same as above)
df["OnlineBackup"].value_counts(dropna=False)

OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

In [26]:
# DeviceProtection :
# values: Yes, No, No internet service
# No internet service if the reason of not having DeviceProtection is "no internet service"        --> inconsistant category
# (same as above)
# (same as above)
# (same as above)
df["DeviceProtection"].value_counts(dropna=False)

DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

In [27]:
# TechSupport :
# values: Yes, No, No internet service
# No internet service if the reason of not having TechSupport is "no internet service"        --> inconsistant category
# (same as above)
# (same as above)
# (same as above)
df["TechSupport"].value_counts(dropna=False)

TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

In [28]:
# StreamingTV :
# values: Yes, No, No internet service
# No internet service if the reason of not having StreamingTV is "no internet service"        --> inconsistant category
# (same as above)
# (same as above)
# (same as above)
df["StreamingTV"].value_counts(dropna=False)

StreamingTV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64

In [29]:
# StreamingMovies :
# values: Yes, No, No internet service
# No internet service if the reason of not having StreamingMovies is "no internet service"        --> inconsistant category
# (same as above)
# (same as above)
# (same as above)
df["StreamingMovies"].value_counts(dropna=False)

StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

In [30]:
# PaperlessBilling :
# indecates receiving invoices electronically instead of papers
# "Yes" if the customer uses electronic billing, else "No"
# convert str --> bool          
df["PaperlessBilling"].value_counts(dropna=False)

PaperlessBilling
Yes    4171
No     2872
Name: count, dtype: int64

In [31]:
# Churn :
# indicates whether the customer left the company or not
# values: Yes, No
# "Yes" if the customer left the company, else "No" 
# convert str --> bool  
df["Churn"].value_counts(dropna=False)

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [32]:
# Contract :
# indicates the customers contract type (Month-to-month,One year,Two year)
# nominal categorical --> stays str
df["Contract"].value_counts(dropna=False)

Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

In [33]:
# PaymentMethod :
# indicates the customers PaymentMethod type (Electronic check,Mailed check,Two year ,Bank transfer (automatic),Credit card (automatic))
# nominal categorical --> stays str
df["PaymentMethod"].value_counts(dropna=False)

PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

In [34]:
# tenure :
# indicates the number of months the customer spent in the company
# stays int 
# min 0  --> indicates the customer is new 
# max 72 --> the customer spent 72 month in the company 
# no strange values 
# mean = 32.371149 & meadian = 29.000000   --> no outlier 
df["tenure"].describe()

count    7043.000000
mean       32.371149
std        24.559481
min         0.000000
25%         9.000000
50%        29.000000
75%        55.000000
max        72.000000
Name: tenure, dtype: float64

In [35]:
# MonthlyCharges
# indicates the amount expected from the customer to pay for services monthly 
# stays float
# min 18.250000  , max 118.750000
# no strange values 
# mean = 32.64.761692 & meadian = 29.70.350000   --> no outlier 
df["MonthlyCharges"].describe()

count    7043.000000
mean       64.761692
std        30.090047
min        18.250000
25%        35.500000
50%        70.350000
75%        89.850000
max       118.750000
Name: MonthlyCharges, dtype: float64

In [36]:
# TotalCharges
# indicates the total amount the customer paid (since his 1st month until now)
# equals tenure * MonthlyCharges 
# no statistics appear as the type is str --> convert to numeric (float) to be able to make calculations on this column (todo in phase 4)
# expected problem --> there maybe missing values, but the type being str preventing this from appearing
df["TotalCharges"].describe()

count     7043
unique    6531
top       20.2
freq        11
Name: TotalCharges, dtype: object

In [37]:
# note that no missing values appeared --> this maybe misleading --> we will never know until we convert to float
df["TotalCharges"].isna().sum()

np.int64(0)

**phase 3**

In [38]:
# 1. missing values : 
# no missing values  
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [39]:
# missing value percentage = 0 for all columns --> could be misleading for (TotalCharges) --> will know after converting in phase 4 
df.isna().mean()*100

customerID          0.0
gender              0.0
SeniorCitizen       0.0
Partner             0.0
Dependents          0.0
tenure              0.0
PhoneService        0.0
MultipleLines       0.0
InternetService     0.0
OnlineSecurity      0.0
OnlineBackup        0.0
DeviceProtection    0.0
TechSupport         0.0
StreamingTV         0.0
StreamingMovies     0.0
Contract            0.0
PaperlessBilling    0.0
PaymentMethod       0.0
MonthlyCharges      0.0
TotalCharges        0.0
Churn               0.0
dtype: float64

In [40]:
# 2. duplicates :
# customerID must be unique 
# check ...
# nunique = number of total rows  = 7043 --> no duplicates 
df["customerID"].nunique()

7043

In [41]:
# 3. Invalid values (examples: empty strings, spaces, weird categories) 
# when using value_counts()                                                   --> used in phase 2 
# 1. empty strings : we used (dropna = false)                                 --> no empty strings (nan values) found  --> this may be misleading for str columns 
# 2. spaces : if there are spaces they also appear                            --> no such spaces found 
# 3. weird categories : 2 inconsistant categories are found                   --> No internet service & No phone service

In [42]:
# 4. outliers :
# min = 18.250000 & max = 118.75000
# mean = 64.761692 , median = 70.350000      
# no outlier
df["MonthlyCharges"].describe()

count    7043.000000
mean       64.761692
std        30.090047
min        18.250000
25%        35.500000
50%        70.350000
75%        89.850000
max       118.750000
Name: MonthlyCharges, dtype: float64

In [43]:
# values filled after converting str --> numeric in pahse 4 (done)
# min =  18.800000  & max = 8684.800000
# mean = 2283.300441 , median = 1397.475000 
# --> no outlier 
# --> high values in TotalCharges are valid and represent long term customers, or customers with high monthly charges,
# --> not something strange, no action needed
df["TotalCharges"].describe()

count     7043
unique    6531
top       20.2
freq        11
Name: TotalCharges, dtype: object

phase 4

In [44]:
'''
# Fix data types
    outcomes (from phase 2) --> (to do in phase 4)
    * "SeniorCitizen"                                                            int --> boolean 
    * "Partner", "Dependents", "PhoneService", "PaperlessBilling", "Churn"       str --> boolean 
    * "MultipleLines"
        1. combine (No phone service) with (No) in MultipleLines column
        2. convert str --> bool
    * "OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV" , "StreamingMovies" 
        1. combine (No internet service) with (No) 
        2. convert str --> bool
    * "TotalCharges" --> convert str --> numeric (float) 

 '''

'\n# Fix data types\n    outcomes (from phase 2) --> (to do in phase 4)\n    * "SeniorCitizen"                                                            int --> boolean \n    * "Partner", "Dependents", "PhoneService", "PaperlessBilling", "Churn"       str --> boolean \n    * "MultipleLines"\n        1. combine (No phone service) with (No) in MultipleLines column\n        2. convert str --> bool\n    * "OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV" , "StreamingMovies" \n        1. combine (No internet service) with (No) \n        2. convert str --> bool\n    * "TotalCharges" --> convert str --> numeric (float) \n\n '

In [45]:
# 1. fix data types 
# convert numeric --> bool
df["SeniorCitizen"] = df["SeniorCitizen"].astype(bool)
df["SeniorCitizen"].dtype

dtype('bool')

In [46]:
# convert str  --> bool
# for all (Partner, Dependents, PhoneService, PaperlessBilling, Churn) cols then map Yes to True and No to False
for col in df.columns :
    if col == "Partner" or col == "Dependents" or col =="PhoneService" or col == "PaperlessBilling" or col =="Churn":
        df[col] = df[col].map({"Yes":True , "No":False})
df [["Partner" , "Dependents" , "PhoneService" , "PaperlessBilling" , "Churn" ]].dtypes

Partner             bool
Dependents          bool
PhoneService        bool
PaperlessBilling    bool
Churn               bool
dtype: object

In [47]:
# convert str --> numeric --> to be able to make calculations on this column and count the missing values if found after converting 
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors= "coerce")
df["TotalCharges"].dtype

dtype('float64')

In [48]:
# 11 missing value in TotalCharges now appeared 
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   bool
 3   Partner           7043 non-null   bool
 4   Dependents        7043 non-null   bool
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   bool
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   bool
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   bool
dtypes: bool(6), float64(2), int64(1), str(12)
memory usage: 866.7 KB

In [49]:
# now we can use .describe()    --> fill min, max, mean, median in phase 3 
df["TotalCharges"].describe()

count    7032.000000
mean     2283.300441
std      2266.771362
min        18.800000
25%       401.450000
50%      1397.475000
75%      3794.737500
max      8684.800000
Name: TotalCharges, dtype: float64

In [50]:
# 2. Handle missing values
# display rows with missing values in TotalCharges column to understand the reason of missingess and decide how to handle it
df[df["TotalCharges"].isna()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,False,True,True,0,False,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,True,Bank transfer (automatic),52.55,NaN,False
753,3115-CZMZD,Male,False,False,True,0,True,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,False,Mailed check,20.25,NaN,False
936,5709-LVOEQ,Female,False,True,True,0,True,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,False,Mailed check,80.85,NaN,False
1082,4367-NUYAO,Male,False,True,True,0,True,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,False,Mailed check,25.75,NaN,False
1340,1371-DWPAZ,Female,False,True,True,0,False,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,False,Credit card (automatic),56.05,NaN,False
3331,7644-OMVMY,Male,False,True,True,0,True,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,False,Mailed check,19.85,NaN,False
3826,3213-VVOLG,Male,False,True,True,0,True,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,False,Mailed check,25.35,NaN,False
4380,2520-SGTTA,Female,False,True,True,0,True,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,False,Mailed check,20.00,NaN,False
5218,2923-ARZLG,Male,False,True,True,0,True,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,True,Mailed check,19.70,NaN,False
6670,4075-WKNIU,Female,False,True,True,0,True,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,False,Mailed check,73.35,NaN,False
6754,2775-SEFEE,Male,False,False,True,0,True,Yes,DSL,Yes,...,No,Yes,No,No,Two year,True,Bank transfer (automatic),61.90,NaN,False

In [51]:
# try to find why values in TotalCharges are missing ? 
# note that for all customers with missing TotalCharges --> tenure = 0 
# This can be explained by the fact that tenure = 0 means the customer is new  (didnt complete his 1st month yet)
# this demonistrates why TotalCharges are missing because the customer didnt pay anything yet 
# i think the best strategy to fill the missing values is to fill with 0 --> as it reflects the real situation (nothing paid yet)

In [52]:
# fill missing values in TotalCharges with 0
df["TotalCharges"]= df["TotalCharges"].fillna(0)

In [53]:
# check if all missing values are filled
# now no missing values 
df[df["TotalCharges"].isna()]

Empty DataFrame
Columns: [customerID, gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn]
Index: []

[0 rows x 21 columns]

In [54]:
# 3. Fix inconsistent categories 
# in phase 2 we found 2 inconsistant categories (No internet service & No phone serves)
# we will map them to "No" because actually they mean the same thing 
# (the customer's reason for not having the service means that the service does not exist)
# and also to reduce redundancy as we have other columns indicating the existence of the service (InternetService & PhoneService)     `

In [55]:
# columns with "No internet service" & "No phone service" inconsistant categories
cols =["MultipleLines","OnlineSecurity","OnlineBackup","DeviceProtection","TechSupport","StreamingTV","StreamingMovies"]

In [56]:
# replace  all "No internet service" & "No phone service"  categories with "No"
for col in cols:
    df[col] = df[col].replace({"No internet service":"No" , "No phone service":"No"})

In [57]:
# display value counts for the columns to check if all "No internet service" & "No phone service" are replaced with "No"
for col in cols:
    print(df[col].value_counts(dropna=False))

MultipleLines
No     4072
Yes    2971
Name: count, dtype: int64
OnlineSecurity
No     5024
Yes    2019
Name: count, dtype: int64
OnlineBackup
No     4614
Yes    2429
Name: count, dtype: int64
DeviceProtection
No     4621
Yes    2422
Name: count, dtype: int64
TechSupport
No     4999
Yes    2044
Name: count, dtype: int64
StreamingTV
No     4336
Yes    2707
Name: count, dtype: int64
StreamingMovies
No     4311
Yes    2732
Name: count, dtype: int64

In [58]:
# after mapping --> 2 categories (Yes,No) --> convert str -->  bool
for col in cols :
        df[col] = df[col].replace({"Yes":True , "No":False})
        df[col] = df[col].astype(bool)

In [59]:
# check if all values are converted to bool and the mapping is done correctly
for col in cols:
    print(df[col].value_counts(dropna=False))
    print(df[col].dtype)

MultipleLines
False    4072
True     2971
Name: count, dtype: int64
bool
OnlineSecurity
False    5024
True     2019
Name: count, dtype: int64
bool
OnlineBackup
False    4614
True     2429
Name: count, dtype: int64
bool
DeviceProtection
False    4621
True     2422
Name: count, dtype: int64
bool
TechSupport
False    4999
True     2044
Name: count, dtype: int64
bool
StreamingTV
False    4336
True     2707
Name: count, dtype: int64
bool
StreamingMovies
False    4311
True     2732
Name: count, dtype: int64
bool

In [60]:
# in phase 5 --> i will extract the feature HasInterntService from the columns above

In [61]:
# 4. Remove useless columns
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [62]:
# customerID is not useful for churn analysis as it does not provide any information about the customer or their behavior,
# it is just an identifier for each customer.
# retain the values in a separate variable (customer_ids) if needed for later use 
# drop customerID column and reflect the changes in the dataframe using inplace = true
customer_ids = df["customerID"] 
df.drop(columns="customerID", inplace=True)
df.columns # now customerID is removed

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [63]:
# check if gender is useful for churn analysis or not
# find the avg churn rate for each gender --> almost the same
df.groupby("gender")["Churn"].mean()

gender
Female    0.269209
Male      0.261603
Name: Churn, dtype: float64

In [64]:
# we conclude that gender is not useful for churn analysis and to reduce the number of features
# retain the values in a separate variable (customer_gender) if needed for later use 
# drop gender column and reflect the changes in the dataframe using inplace = true        
customer_gender = df["gender"]
df.drop(columns="gender", inplace=True)
df.columns # now gender is removed

Index(['SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges',
       'TotalCharges', 'Churn'],
      dtype='str')

In [65]:
# save the dropped columns in a list to be able to use them later if needed
dropped_columns = ["customer_ids","customer_gender"]

phase 5

In [66]:
# feature 1 :
# extract new feature is_month_to_month from Contract column 
# it indicates the customers contract type (month or not) which is expected to affect churn analysis
# is_month_to_month 1 if Contract == "Month-to-month"  else 0
df["is_month_to_month"] = df["Contract"].apply(lambda x : 1 if x == "Month-to-month" else 0  )

In [67]:
# feature 2 :
# i can extract a more specific feature than is_month_to_month indicating the contract length group (month / year / two-year)
# extract new feature contract_length_group from Contract column
# it indicates the customers contract type (month or year or two-year) which is expected to affect churn analysis
def contract_length_group (contract) :
    if contract == "Month-to-month" :
        return "month"
    elif contract == "One year" :
        return "year"
    else:
        return "two-year"
df["contract_length_group"] = df["Contract"].apply(contract_length_group)

In [68]:
# feature 3 :
# extract avg_spend_per_month feature from TotalCharges and tenure columns
# avg_spend_per_month = TotalCharges / (tenure + 1)   --> add 1 to tenure to avoid division by zero for new customers (tenure = 0)
# TotalCharges accumulates over time, while this represents the actual monthly value regardless of the duration the customer spent in the company
# this allows fair comparison between new and long-term customers, 
# it helps analyze churn by comparing past average with current price
df["avg_spend_per_month"] = df["TotalCharges"] / ( df["tenure"] + 1 )

In [69]:
# feature 4 :
# extract new feature high_monthly_charge from MonthlyCharges column
# high_monthly_charge 1 if MonthlyCharges > median else 0 
def monthly_charge_seg (charge) :
        if charge  > df["MonthlyCharges"].median():
            return "high"
        else:
            return "low"
df["high_monthly_charge"] = df["MonthlyCharges"].apply(monthly_charge_seg)

In [70]:
# feature 5 :
# extract new feature high_total_charge from TotalCharges column
# high_total_charge 1 if TotalCharges > median else 0
median_charge = df["TotalCharges"].median()
df["high_total_charge"] = df["TotalCharges"].apply( lambda x : "high" if x > median_charge else "low" )

In [71]:
# feature 6 :
# extract new feature new_customer from tenure column
# new_customer 1 if tenure <= 3 else 0
df["new_customer"] = df["tenure"].apply(lambda x : x<=3)

In [72]:
# feature 7 :
# extract new feature long_term_customer from tenure column
# long_term_customer 1 if tenure >= 24 else 0
df["long_term_customer"] = df["tenure"].apply(lambda x : x>=24 )

In [73]:
# check  --> must be no intersection 
df[df["new_customer"] & df ["long_term_customer"] ]

Empty DataFrame
Columns: [SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn, is_month_to_month, contract_length_group, avg_spend_per_month, high_monthly_charge, high_total_charge, new_customer, long_term_customer]
Index: []

[0 rows x 26 columns]

In [74]:
# feature 8 :
# extract new feature uses_electronic_check from PaymentMethod column
# uses_electronic_check 1 if PaymentMethod == "Electronic check" else 0
df["uses_electronic_check"] = df["PaymentMethod"].apply(lambda x : 1 if x == "Electronic check" else 0 )

In [75]:
# feature 9 :
# extract new feature paperless_billing from PaperlessBilling column
# paperless_billing (1 if PaperlessBilling == "Yes") else 0
# paperless_billing (0/1)
df["paperless_billing"] = df["PaperlessBilling"].apply(lambda x : 1 if x==True else 0 )

In [76]:
# feature 10 :
# extract new feature has_internet_service from InternetService column
# has_internet_service 1 if InternetService != "No" else 0
df["has_internet_service"] = df["InternetService"]!= "No"

In [77]:
# feature 11 :
# extract new feature Diff between MonthlyCharges and avg_spend_per_month to analyze the change in the customers spending behavior
# Diff = MonthlyCharges - avg_spend_per_month
df["Diff"] = df["MonthlyCharges"] - df["avg_spend_per_month"]

In [78]:
# feature 12 :
# extract new feature price_changed from Diff column to analyze the effect of sudden price changes on churn
# if the diff is positive and high (>10) --> this means a sudden price increase happens --> likely to churn
# if the diff is negative                --> this means a sudden price decrease happens --> likely to stay
df["price_changed"] = df["Diff"].apply(lambda x : 1 if x > 10 else 0 )

In [79]:
# feature 13 : 
# extract new feature is_automatic from PaymentMethod column
# indicate whether the customer uses an automatic payment method (bank transfer or credit card) or not (electronic check or mailed check)
# is_automatic 1 if PaymentMethod is (Bank transfer (automatic) or Credit card (automatic)) else 0
df["is_automatic"] = df["PaymentMethod"].apply(lambda x : 1 if x in ["Bank transfer (automatic)","Credit card (automatic)"] else 0 )

In [80]:
# feature 14 :
# extract new feature payment_category from PaymentMethod column
# it indicates the payment method type (automatic) or not (electronic check or mailed check) which is expected to affect churn analysis
# why grouping payment methods into 2 categories (automatic vs non-automatic) is not accurate ? 
# because customers who pay with electronic check or mailed check have different churn rates as shown below in df.groupby("PaymentMethod")["Churn"].mean()
# for some analysis its not correct to ignore this difference
def payment_category(method):
    if 'automatic' in method:
        return 'Automatic'
    else:
        return method 

df['payment_category'] = df['PaymentMethod'].apply(payment_category)
df.groupby("payment_category")["Churn"].mean()

payment_category
Automatic           0.159817
Electronic check    0.452854
Mailed check        0.191067
Name: Churn, dtype: float64

In [81]:
df.dtypes

SeniorCitizen               bool
Partner                     bool
Dependents                  bool
tenure                     int64
PhoneService                bool
MultipleLines               bool
InternetService              str
OnlineSecurity              bool
OnlineBackup                bool
DeviceProtection            bool
TechSupport                 bool
StreamingTV                 bool
StreamingMovies             bool
Contract                     str
PaperlessBilling            bool
PaymentMethod                str
MonthlyCharges           float64
TotalCharges             float64
Churn                       bool
is_month_to_month          int64
contract_length_group        str
avg_spend_per_month      float64
high_monthly_charge          str
high_total_charge            str
new_customer                bool
long_term_customer          bool
uses_electronic_check      int64
paperless_billing          int64
has_internet_service        bool
Diff                     float64
price_changed              int64
is_automatic               int64
payment_category             str
dtype: object

In [82]:
# is_month_to_month        --> 2 values (0,1) representing (false,true)  --> bool
# uses_electronic_check    --> 2 values (0,1) representing (false,true)  --> bool 
# price_changed            --> 2 values (0,1) representing (false,true)  --> bool
# is_automatic             --> 2 values (0,1) representing (false,true)  --> bool
# paperless_billing        --> 2 values (0,1) representing (false,true)  -->
# im not gonna convert it to bool because there alreaady exist the column PaperlessBilling with the same info but in bool 
# so no need to have 2 columns with the same info in the same types

In [83]:
# convert from int to bool
for col in df.columns:
    if col == "is_month_to_month"  or col =="uses_electronic_check" or col == "price_changed"or col == "is_automatic" :
        df[col] = df[col].astype(bool)

In [84]:
# check if the conversion is done correctly
df[["is_month_to_month" ,"uses_electronic_check", "price_changed" , "is_automatic"]].dtypes

is_month_to_month        bool
uses_electronic_check    bool
price_changed            bool
is_automatic             bool
dtype: object

phase 6

In [85]:
'''
Confirm no invalid dtypes remain
Confirm missing values are handled (or justified)
Provide:
final shape
list of dropped columns
list of newly added features
'''

'\nConfirm no invalid dtypes remain\nConfirm missing values are handled (or justified)\nProvide:\nfinal shape\nlist of dropped columns\nlist of newly added features\n'

In [86]:
# now all features are in the correct types and ready for analysis in phase 6
df.dtypes

SeniorCitizen               bool
Partner                     bool
Dependents                  bool
tenure                     int64
PhoneService                bool
MultipleLines               bool
InternetService              str
OnlineSecurity              bool
OnlineBackup                bool
DeviceProtection            bool
TechSupport                 bool
StreamingTV                 bool
StreamingMovies             bool
Contract                     str
PaperlessBilling            bool
PaymentMethod                str
MonthlyCharges           float64
TotalCharges             float64
Churn                       bool
is_month_to_month           bool
contract_length_group        str
avg_spend_per_month      float64
high_monthly_charge          str
high_total_charge            str
new_customer                bool
long_term_customer          bool
uses_electronic_check       bool
paperless_billing          int64
has_internet_service        bool
Diff                     float64
price_changed               bool
is_automatic                bool
payment_category             str
dtype: object

In [87]:
# cofirm no missing values in TotalCharges column after filling
df["TotalCharges"].isna().sum()

np.int64(0)

In [88]:
# final shape after dropping useless columns and adding new features
df.shape
df

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,...,high_total_charge,new_customer,long_term_customer,uses_electronic_check,paperless_billing,has_internet_service,Diff,price_changed,is_automatic,payment_category
0,False,True,False,1,False,False,DSL,False,True,False,...,low,True,False,True,1,True,14.925000,True,False,Electronic check
1,False,False,False,34,True,False,DSL,True,False,True,...,high,False,True,False,0,True,2.964286,False,False,Mailed check
2,False,False,False,2,True,False,DSL,True,True,False,...,low,True,False,False,1,True,17.800000,True,False,Mailed check
3,False,False,False,45,False,False,DSL,True,False,True,...,high,False,True,False,0,True,2.283696,False,True,Automatic
4,False,False,False,2,True,False,Fiber optic,False,False,False,...,low,True,False,True,1,True,20.150000,True,False,Electronic check
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,False,True,True,24,True,True,DSL,True,False,True,...,high,False,True,False,1,True,5.180000,False,False,Mailed check
7039,False,True,True,72,True,True,Fiber optic,False,True,True,...,high,False,True,False,1,True,2.338356,False,True,Automatic
7040,False,True,True,11,False,False,DSL,True,False,False,...,low,False,False,True,1,True,0.729167,False,False,Electronic check
7041,True,True,False,4,True,True,Fiber optic,False,False,False,...,low,False,False,False,1,True,13.080000,True,False,Mailed check
7042,False,False,False,66,True,False,Fiber optic,True,False,True,...,high,False,True,False,1,True,3.493284,False,True,Automatic

In [89]:
# list all dropped columns
dropped_columns

['customer_ids', 'customer_gender']

In [90]:
# list all newly added features
features = [
    "is_month_to_month",
    "contract_length_group",
    "avg_spend_per_month",
    "high_monthly_charge",
    "high_total_charge",
    "new_customer",
    "long_term_customer",
    "uses_electronic_check",
    "paperless_billing",
    "has_internet_service",
    "Diff",
    "price_changed", 
    "is_automatic",
    "payment_category"
]
features

['is_month_to_month',
 'contract_length_group',
 'avg_spend_per_month',
 'high_monthly_charge',
 'high_total_charge',
 'new_customer',
 'long_term_customer',
 'uses_electronic_check',
 'paperless_billing',
 'has_internet_service',
 'Diff',
 'price_changed',
 'is_automatic',
 'payment_category']

phase 7

In [91]:
# 1.
# *does contract type affect churn? yes
# *hypothesis: more duration contract --> responsibilities or cost --> less likely to churn
#              short contract         --> more easy to leave       --> no responsibilities or cost
# *analysis of the result : 
#  the results confirm our hypothesis --> long-term customers churn rate (0.14%) is less than non long-term customers churn rate (0.41) 
#  may be the reason customers with short contract joined is only to test the services --> if they are not satisfied --> churn 
# *business insight :
#  the company should focus on short contract custorms , and maybe providing discounts or changing their contract to be long term
df.groupby("Contract")["Churn"].mean()

Contract
Month-to-month    0.427097
One year          0.112695
Two year          0.028319
Name: Churn, dtype: float64

In [92]:
# 2. 
# *do long-term customers affect churn ? 
# *hypothesis: long term customers churn less because they are more committed to the company and have been using the services for a long time,
#              (seems to be satisfied)
# *analysis of the result : 
#  the results confirm our hypothesis --> long-term customers churn rate (0.14%) is less than non long-term customers churn rate (0.41) 
# *business insight :
#  the company should focus on new customers to prevent them from churning and try to convert them to long-term customers or 
#  by giving them good services to encourage them to stay

In [93]:
# display the churn rate for long_term_customer vs non long_term_customer to use in the analysis below (hypo2)
# we reached out that long_term_customer are more likely to churn than non long_term_customers
df.groupby("long_term_customer")["Churn"].mean()

long_term_customer
False    0.419769
True     0.142857
Name: Churn, dtype: float64

In [94]:
# 3. 
# *does partner & dependents affect churn ?
# *hypothesis: single customers churn more than customers with Partners and Dependents --> more responsibility
# *analysis of the results:
#  i will analyze the effect of Partner and Dependents on churn (togother) 
#  --> no partner & no dependents  churn rate (34%)    --> easy to churn      (no responsibilities) 
#  --> partner    & dependents     churn rate (14%)    --> not easy to churn  (more responsibilities) 
#  --> partner    & no dependents  churn rate (25%)    larger than   
#  --> no partner & dependents     churn rate (21%) 
#      having a partner is more likely to churn than having only dependents --> (maybe bcz dependents responsibility more than a partner)
# *buisiness insight : 
#  the company should try to retain single customers by giving them discounts, and long-term contracts 
#  for families the company should focus on increasing the benifit from them , by selling them more services or upgrade the services they use

In [95]:
# display the churn rate for  customers with Dependents vs without dependents & with partner vs without partner to use in the analysis above
df.groupby(["Dependents","Partner"])["Churn"].mean()

Dependents  Partner
False       False      0.342378
            True       0.254083
True        False      0.213296
            True       0.142367
Name: Churn, dtype: float64

In [96]:
# 4. 
# *does Payment Method affect churn ? 
# *hypothesis: customers pay automatically churn less -->  the least effort. 
#              customers pay with electronic checks churn less than customers pay with mailed checks--> less effort
# *analysis of the result : 
#  1st part of hypothesis confirmed --> automatic (15%) --> Lowest churn due to least effort
#  2nd part of the hypothesis, there is contradiction: 
#  Electronic Check (45%) has higher churn than Mailed Check (19%), although Electronic Check is "easier" to use.
#  we have to find another reason to justify this unexpected result. check these factors: 
#  factor 1 (price_changed)        
#  factor 2 (contract type)                        
#  factor 3 (service type)                           
# *business insight :
# the company should focus on customers using electronic checks (highest churn) especially who use fiber optic and face price changes
# by encouraging them to switch to automatic payments through discounts

In [97]:
# what column to use to analyze payment method effect on churn ?

In [98]:
# 1. choice 1 (is_automatic)
# gives general idea about the effect of using automatic payment method on churn  --> automatic less likely to churn 
# but it combines customers who pay with electronic check or mailed check in one group (not automatic) and treats them as one group 
# which is not accurate as they have different churn rates (as shown below in df.groupby("PaymentMethod")["Churn"].mean() )
# the solution is to extract a more specific feature indicating the payment method type 
# bank transfer, credit card --> combine into automatic 
# kepp Electronic check and Mailed check without combining them 
df.groupby("is_automatic")["Churn"].mean()  # --> very general --> not gonna use it

is_automatic
False    0.346744
True     0.159817
Name: Churn, dtype: float64

In [99]:
# 2. choice 2 (PaymentMethod) --> the original col
df.groupby("PaymentMethod")["Churn"].mean() # --> can be more simplified --> not gonna use it

PaymentMethod
Bank transfer (automatic)    0.167098
Credit card (automatic)      0.152431
Electronic check             0.452854
Mailed check                 0.191067
Name: Churn, dtype: float64

In [100]:
# 3. choice 3 (payment_category)
df.groupby("payment_category")["Churn"].mean() # --> more simplified and accurate (the best to analyze churn)

payment_category
Automatic           0.159817
Electronic check    0.452854
Mailed check        0.191067
Name: Churn, dtype: float64

In [101]:
# trying to find factors affecting the churn rate for customers using electronic checks >  mailed checks 
# by analyzing the effect of price changes, contract type, and service type on churn for each payment category alone
# the automatic category is not mentioned here because the hypothesis about it is already confirmed in the analysis above

In [102]:
# how price changes affect churn for payment categories ?
df[df["payment_category"]!="Automatic"].groupby(["payment_category","price_changed"])["Churn"].mean()

payment_category  price_changed
Electronic check  False            0.357437
                  True             0.697289
Mailed check      False            0.114754
                  True             0.486405
Name: Churn, dtype: float64

In [103]:
# note that 28% of customers who pay with electronic check, 20% of customers who pay with mailed check face price changes 
# when price changes happen, the churn rate of customers using Electronic check (69%) > the churn rate of those using Mailed check (48%)
# important to say that before any price changes, ustomers useing electronic check already have high probabilty to churn but price changes increases this probability 
# while for those who use mailed check, when no price changes, their probability to churn is already little but price changes increases this property
# this supports the fact that churn rate for customers with elecronic check > churn rate for customers with mailed check
# the fact that customers using electronic check churn alot even when there is no price change tells us that there is other reasons for this.
df[df["payment_category"]!="Automatic"].groupby("payment_category")["price_changed"].mean()

payment_category
Electronic check    0.280761
Mailed check        0.205335
Name: price_changed, dtype: float64

In [104]:
# how contract type affect churn for payment categories ?
df[df["payment_category"]!="Automatic"].groupby(["payment_category","is_month_to_month"] )["Churn"].mean()

payment_category  is_month_to_month
Electronic check  False                0.149515
                  True                 0.537297
Mailed check      False                0.036161
                  True                 0.315789
Name: Churn, dtype: float64

In [105]:
# note that 78% of customers who pay with electronic check and 55 of customers who pay with mailed check are month-to-month customers
# this may be one of the reasons behind the high churn rate for customers who pay with electronic checks 
# as those customers are more likely to churn (53%) compared to mailed check users (31%).
df[df["payment_category"]!="Automatic"].groupby("payment_category")["is_month_to_month"].mean()

payment_category
Electronic check    0.782241
Mailed check        0.553970
Name: is_month_to_month, dtype: float64

In [106]:
# how InternetService type affect churn for payment categories ?
df[df["payment_category"]!="Automatic"].groupby(["payment_category","InternetService"])["Churn"].mean()

payment_category  InternetService
Electronic check  DSL                0.319444
                  Fiber optic        0.532288
                  No                 0.122951
Mailed check      DSL                0.207178
                  Fiber optic        0.426357
                  No                 0.095816
Name: Churn, dtype: float64

In [107]:
# note that most of customers who pay with electronic check use Fiber optic (larger number)
# while most of customers using mailed check have no internet service 
# this may be one of the reasons behind the high churn rate for customers who pay with electronic checks 
# as those customers are more likely to churn (53%) compared to maile check users (0.09%).
df[df["payment_category"]!="Automatic"].groupby("payment_category")["InternetService"].value_counts()

payment_category  InternetService
Electronic check  Fiber optic        1595
                  DSL                 648
                  No                  122
Mailed check      No                  741
                  DSL                 613
                  Fiber optic         258
Name: count, dtype: int64

In [108]:
# 5.
# Does price impact churn? yes
# analysis on high_monthly_charge or high_total_charge ? 
# i will choose high_monthly_charge for analysis
# justification 
# --> i did not use TotalCharges because its obvious that older customers have higher total charges and new customers have lower total charges 
# --> this doesnt tell us anything clear about churn 
# --> but i chose MonthlyCharges as it tells the current price the customer pays, from it we can reach some findings to analyze churn 

# --> i will also use 'avg_spend_per_month' to check for recent changes.
# --> i will look at the diff --> if current MonthlyCharges is higher than the average, the customer is more likely to be unhappy.
# --> price changes make people leave more than just price being high  
# --> sudden prices changes may bcz the customer upgraded to a more expensive plan, or the price of the plan increased,
#     or the customer is using more services than before.
# *business insight :
#  the company should offer discounts to reduce churn for high-paying customers

In [109]:
# display churn rate for customers with high monthly charge vs low monthly charge
# chrn rate is higher for customers with high monthly charge
# this analysis is not sufficient 
# why customers with high monthly charges churn more ? is it only due to high price ? 
# why customers with low monthly charges churn less ? is it only due to low price ? 
df.groupby("high_monthly_charge")["Churn"].mean()

high_monthly_charge
high    0.351920
low     0.179138
Name: Churn, dtype: float64

In [110]:
# display churn rate for customers with high monthly charge vs low monthly charge and with price changes vs no parice changes
# High Price & No price changes (27%) --> Customer pays a lot but used to it 
# High Price & price changes    (71%) --> Customer pays a lot and then foun increase in price. 
# Low Price  & No price changes (11%) --> Customer pays little with no changes in price --> (perfect)--> makes sense that its the least percentage of churn
# Low Price  & price changes    (52%) --> Customer paid little and then found increase in price.
# note stability is the most important factor, customers leave due to high changes regardless of the price(as also who pays low leave due to changes)
# However, it is also clear that a price change with higher monthly charge generally leads to a higher churn rate.
df.groupby(["high_monthly_charge", "price_changed"])["Churn"].mean()

high_monthly_charge  price_changed
high                 False            0.273074
                     True             0.710900
low                  False            0.113590
                     True             0.519298
Name: Churn, dtype: float64