Phase 1

In [2]:
import pandas as pd 
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [3]:
df.shape

(7043, 21)

In [4]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [5]:
df.dtypes

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [6]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [7]:
df["Churn"].value_counts(dropna=False)

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [8]:
#imbalanced

In [ ]:
'''
This telecom company dataset describes the customers including their personal info, the duration they have spent with the company,
the services they use and the financial relationship between the customer and the company.

Our target is to answer to the question: "Why customers leave the company and who are they?" based on deep data analysis.
This enables us to develope comprehensive strategies to reduce customer loss. 

From the initial overview on the dataset, some issues were observed. First, "SeniorCitizen" should be converted from numeric to bool.
Second, the "TotalCharges" column should be converted from str to numeric type. Third, the "churn" column should be converted from str to bool.
Finally, the "churn" target variable is imbalanced

'''

phase 2

In [ ]:
Create a table:

Column	Current dtype	Correct type	Reason
Focus on:

IDs (like customerID)
Binary columns (Yes/No)
Columns stored as text but should be numeric (common issue: TotalCharges)
Deliverable
A column audit table
3 columns that can easily cause wrong analysis if typed incorrectly

In [33]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [67]:
df["customerID"].isna().sum()

np.int64(0)

In [66]:
df[["customerID"]].nunique()

customerID    7043
dtype: int64

In [35]:
df["gender"].value_counts(dropna=False)

gender
Male      3555
Female    3488
Name: count, dtype: int64

In [87]:
'''
check all values have (0,1) representing (true,false) --> convert to bool
check all values  have (yes/no)  only --> convert to bool
"SeniorCitizen"  int 
"Partner", "Dependents", "PhoneService", "PaperlessBilling","Churn" 
'''

'\ncheck all values have (0,1) representing (true,false) --> convert to bool\ncheck all values  have (yes/no)  only --> convert to bool\n"SeniorCitizen"  int \n"Partner", "Dependents", "PhoneService", "PaperlessBilling","Churn" \n'

In [ ]:
# convert int --> bool
df["SeniorCitizen"].value_counts(dropna=False)

In [ ]:
df["SeniorCitizen"] = df["SeniorCitizen"].astype(bool)

In [95]:
# convert str --> bool 
df["Partner"].value_counts(dropna=False)

Partner
No     3641
Yes    3402
Name: count, dtype: int64

In [96]:
df["Partner"] = df["Partner"].astype(bool)

In [ ]:
# convert str --> bool 
df["Dependents"].value_counts(dropna=False)

Dependents
No     4933
Yes    2110
Name: count, dtype: int64

In [97]:
df["Dependents"] = df["Dependents"].astype(bool)

In [ ]:
# convert str --> bool 
df["PhoneService"].value_counts(dropna=False)

PhoneService
Yes    6361
No      682
Name: count, dtype: int64

In [ ]:
df["PhoneService"] = df["PhoneService"].astype(bool)

In [ ]:
# dont convert str --> bool 
df["MultipleLines"].value_counts(dropna=False)

MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

In [ ]:
# dont convert str --> bool 
df["InternetService"].value_counts(dropna=False)

InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

In [ ]:
# dont convert str --> bool 
df["OnlineSecurity"].value_counts(dropna=False)

OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

In [ ]:
# dont convert str --> bool 
df["DeviceProtection"].value_counts(dropna=False)

DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

In [ ]:
# dont convert str --> bool 
df["TechSupport"].value_counts(dropna=False)

TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

In [ ]:
# dont convert str --> bool 
df["StreamingTV"].value_counts(dropna=False)

StreamingTV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64

In [ ]:
# dont convert str --> bool 
df["StreamingMovies"].value_counts(dropna=False)

StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

In [ ]:
# convert str --> bool 
df["PaperlessBilling"].value_counts(dropna=False)

PaperlessBilling
Yes    4171
No     2872
Name: count, dtype: int64

In [98]:
df[["PhoneService" , "Churn"]] = df[["PhoneService" , "Churn"]].astype(bool)

In [ ]:
df["Contract"].value_counts(dropna=False)

Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

In [68]:
df["tenure"].describe()

count    7043.000000
mean       32.371149
std        24.559481
min         0.000000
25%         9.000000
50%        29.000000
75%        55.000000
max        72.000000
Name: tenure, dtype: float64

In [75]:
df["PaymentMethod"].value_counts(dropna=False)

PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

In [77]:
df["MonthlyCharges"].describe()

count    7043.000000
mean       64.761692
std        30.090047
min        18.250000
25%        35.500000
50%        70.350000
75%        89.850000
max       118.750000
Name: MonthlyCharges, dtype: float64

In [84]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors= "coerce")
df["TotalCharges"].dtype

dtype('float64')

In [85]:
df["TotalCharges"].describe()

count    7032.000000
mean     2283.300441
std      2266.771362
min        18.800000
25%       401.450000
50%      1397.475000
75%      3794.737500
max      8684.800000
Name: TotalCharges, dtype: float64

In [ ]:
# convert str --> bool 
df["Churn"].value_counts(dropna=False)

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [44]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No